# Generated by Django 5.0.6 on 2024-06-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата Створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Оновлення')),
                ('title', models.CharField(default='Без бренду', max_length=100, unique=True, verbose_name='Назва бренду')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип бренду')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'db_table': 'product_brand',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Звичайна ціна')),
                ('special_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна зі знижкою')),
                ('discount_percentage', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Відсоток знижки')),
            ],
            options={
                'verbose_name': 'Ціна',
                'verbose_name_plural': 'Ціни',
                'db_table': 'product_price',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата Створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Оновлення')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Назва магазину')),
                ('city', models.CharField(max_length=255, verbose_name='Місто')),
                ('is_displayed', models.BooleanField(choices=[(False, 'Деактивовано'), (True, 'Активовано')], db_index=True, default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
                'db_table': 'product_store',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата Створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Оновлення')),
                ('title', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'product_category',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата Створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Оновлення')),
                ('title', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('description', models.TextField(blank=True, verbose_name='Опис товару')),
                ('is_stock', models.BooleanField(verbose_name='Наявність')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='products.brand', verbose_name='Назва бренду')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='products.category', verbose_name='Категорії')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices', to='products.price', verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'db_table': 'product',
                'ordering': (models.Case(models.When(price__special_price__gt=0, then='price__special_price'), default='price__regular_price'), 'price__regular_price'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продуктів',
                'db_table': 'product_image',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_images', to='products.productimage', verbose_name='Фото товару'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stores', to='products.store', verbose_name='Назва магазину'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'store')},
        ),
    ]
